---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: "{{ .Values.server }}"
    email: "{{ .Values.email }}"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ .Values.email }}"
    privateKeySecretRef:
      name: letsencrypt-prod-dns01
    solvers:
    - selector:
        dnsZones:
          - "{{ .Values.domain_name }}"
          - "*.{{ .Values.domain_name }}"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: DIKER8JEXAMPLE # optional, see policy above
          role: arn:aws:iam::YYYYYYYYYYYY:role/dns-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-prod
  namespace : dev
spec:
  secretName: wildcard-prod
  issuerRef:
    name: letsencrypt-prod-dns01
    kind: ClusterIssuer
  commonName: "*.{{ .Values.domain_name }}"
  dnsNames:
  - "*.{{ .Values.domain_name }}"
